config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  get 'persons/profile', as: 'user_root'
  match '/persons/add_table', to: 'persons#add_table', via: 'post'
  match '/persons/remove_table', to: 'persons#remove_table', via: 'delete'

end

app/models/poker_table.rb
class PokerTable < ActiveRecord::Base
  has_many :user_tables
  has_many :users, through: :user_tables

  validates :name, presence: true, length: { maximum: 30 }
  validate :count_of_users

  def count_of_users
    return if users.blank?
    errors.add('The limit of users number is 6') if users.size > 6
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_tables
  has_many :poker_tables, through: :user_tables
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_associated :poker_tables
end

app/models/user_table.rb
class UserTable < ActiveRecord::Base
  belongs_to :user
  belongs_to :poker_table
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  before_filter :authenticate_user!

  def profile
    @user_tables = current_user.poker_tables.all
    @not_available_tables = PokerTable.where('start_date < ?', Time.now)
    @available_tables = PokerTable.find_by_sql(['select poker_tables.* from poker_tables
                                                  inner join user_tables on (poker_tables.id = user_tables.poker_table_id)
                                                    group by (poker_tables.id) having (count(user_tables.user_id) < 6)
                                                      union select * from poker_tables where id not in (select poker_table_id from user_tables)']) - @not_available_tables - @user_tables
  end

  def add_table
    table = PokerTable.find(params[:table_id])
    current_user.poker_tables << table
    redirect_to user_root_path
  end

  def remove_table
    table = PokerTable.find(params[:table_id])
    current_user.poker_tables.destroy(table)
    redirect_to user_root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/home/index.html.erb
<%= render 'layouts/signed_in' %>

app/views/layouts/_signed_in.erb
<% if user_signed_in? %>
    <span>Hi, <%= current_user.email %></span>
    <%= link_to 'Log out', destroy_user_session_path, :method => :delete %>
<% else %>
    <%= link_to 'Log in', new_user_session_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PokerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
  <h1>Poker application</h1>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </div>
</div>
</body>
</html>

app/views/persons/profile.html.erb
<%= render 'layouts/signed_in' %>
<div class="row">
  <div class="col-md-4">
    <h2>My tables</h2>
    <div class="row">
      <% @user_tables.each do |user_table| %>
          <div class="col-md-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-9 text-right">
                    <div class="huge"><%= user_table.name %></div>
                  </div>
                </div>
              </div>
              <%= link_to persons_remove_table_path(table_id: user_table.id),method: :delete, data: { confirm: "Are you sure?" } do %>
                <div class="panel-footer">
                  <span class="pull-left"> Left game </span>
                  <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                  <div class="clearfix"></div>
                </div>
              <% end %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <h2>Available tables</h2>
    <div class="row">
      <% @available_tables.each do |user_table| %>
          <div class="col-md-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-9 text-right">
                    <p>Time before start: <%= distance_of_time_in_words user_table.start_date, Time.now %></p>
                    <div class="huge"><%= user_table.name %></div>
                  </div>
                </div>
              </div>
              <%= link_to persons_add_table_path(table_id: user_table.id), method: :post  do %>
                <div class="panel-footer">
                  <span class="pull-left"> Join game </span>
                  <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                  <div class="clearfix"></div>
                </div>
              <% end %>
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-4">
    <h2>Not available tables</h2>
    <div class="row">
      <% @not_available_tables.each do |user_table| %>
          <div class="col-md-6">
            <div class="panel panel-primary">
              <div class="panel-heading">
                <div class="row">
                  <div class="col-xs-9 text-right">
                    <div class="huge"><%= user_table.name %></div>
                  </div>
                </div>
              </div>
              <a href="#">
                <div class="panel-footer">
                  <span class="pull-left"> -----  </span>
                  <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                  <div class="clearfix"></div>
                </div>
              </a>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<!-- /.row -->